// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqmmgyoviwhgqvzqbbja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxbW1neW92aXdoZ3F2enFiYmphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwOTQ2NzMsImV4cCI6MjA3MDY3MDY3M30.FWDd7upp_L0v1iOv0RTlyVIV1spI3hOI_7c5OmLmJdo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});